### ISSUE TITLE
Error Attribute replacement

### ISSUE THREAD

**Issue by jgribonvald** [GIP-RECIA/flash-info-portlet#2]
Bad managment of url replacment cause :
```
la servlet flash-info-portlet a lancé une exception
java.lang.StringIndexOutOfBoundsException: String index out of range: -2
	at java.lang.String.substring(String.java:1960)
	at org.esco.portlet.service.PortletService.getAttributeToReplace(PortletService.java:37)
	at org.esco.portlet.mvc.portlet.MainController.showMainView(MainController.java:82)
```

**Comment by mcisse3007** [comment]
Corrigé
